---
apiVersion: v1
kind: ConfigMap
metadata:
  name: l5d-config
data:
  config.yaml: |-
    admin:
      port: 9990

    namers:
    - kind: io.l5d.k8s

    routers:
    - protocol: http
      identifier:
        kind: io.l5d.http.ingress
      servers:
        - port: 80
          ip: 0.0.0.0
          clearContext: true
        - port: 1080
          ip: 0.0.0.0
          clearContext: true
      dtab: |
        /svc => /#/io.l5d.k8s ;
        /split => /#/io.l5d.k8s ;
        /svc/team-multiplication-operator/my-http/multiplication-operator => 1 * /split/team-multiplication-operator/my-http/multiplication-operator-build-123 & 8 * /split/team-multiplication-operator/my-http/multiplication-operator ;

    usage:
      orgId: linkerd-examples-ingress
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: l5d
  name: l5d
spec:
  template:
    metadata:
      labels:
        app: l5d
    spec:
      hostNetwork: true
      volumes:
      - name: l5d-config
        configMap:
          name: "l5d-config"
      containers:
      # - name: konfd
      #   image: gcr.io/hightowerlabs/konfd:v0.0.4
      #   args:
      #   - -configmap dtab-template
      #   resources:
      #     requests:
      #       cpu: 100m
      #       memory: 30Mi
      # - name: l5d-updater
      #   image: buoyantio/linkerd:0.9.1
      #   cmd: "bash -c 'while true; do namerctl dtab update default -f /opt/shared/dtab-templated; sleep ${SLEEP_DURATION}; done;"
      #   env:
      #   - name: SLEEP_DURATION
      #     value: "10"
      - name: l5d
        image: buoyantio/linkerd:0.9.1
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        args:
        - /io.buoyant/linkerd/config/config.yaml
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: not-socks
          containerPort: 1080
          hostPort: 1080
        - name: admin
          containerPort: 9990
        volumeMounts:
        - name: "l5d-config"
          mountPath: "/io.buoyant/linkerd/config"
          readOnly: true

      - name: kubectl
        image: buoyantio/kubectl:v1.4.0
        args: ["proxy", "-p", "8001"]
---
apiVersion: v1
kind: Service
metadata:
  name: l5d
spec:
  selector:
    app: l5d
  type: NodePort
  clusterIP: 10.3.0.5
  ports:
  - name: http
    port: 80
  - name: admin
    port: 9990
    nodePort: 30999
