---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: edge-gateway
  annotations:
    kubernetes.io/ingress.class: "linkerd"
  labels:
    app: edge-gateway
    environment: preprod
spec:
  rules:
  - host: api.calculator.com
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: my-http
  # This represents all host values that exist in the Puppet/Chef/Ansible config
  - host: division-operator.calculator.com
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: my-http
  # The following config would be used without any rewrite in NGINX.
  # If you use the following, you will end up with a 404 from Go rather than NGINX.
  # We would have to use path to identify us but linkerd doesn't support rewrites *in Ingress objects*
  # See: https://github.com/kubernetes/contrib/tree/d3b2b2d2b99abaf74712db9fce2dabf1344f29e5/ingress/controllers/nginx/examples/rewrite
  # - host: "api.calculator.com"
  #   http:
  #     paths:
  #     - path: "/api/{{ $root.serviceName }}/operate"
  #       backend:
  #         serviceName: "{{ $root.serviceName }}"
  #         servicePort: "{{ $root.portName }}"
