---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: edge-gateway
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - name: first-thing
    targetPort: my-http
    port: 80
    nodePort: 31111
  selector:
    app: nginx
