---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: edge-gateway
data:
  nginx.conf: |-
    events {
      worker_connections  1024;
    }

    http {
      server {
        listen 80;
        server_name _;
        location / {
          proxy_pass       http://l5d.default.svc.cluster.local:81;
          proxy_set_header Host            $host.external;
          proxy_set_header X-Forwarded-For $remote_addr;
        }
      }
    }
